services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: e-library

    ports:
      - "127.0.0.1:3000:3000"

    env_file:
      - /data-disk/applications/elibrary/e-library/.env

    restart: unless-stopped
